module ExactEncoder(
  input  [2:0] io_b_bits, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_neg, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_zero, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_two, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_one // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
);
  wire  b1 = io_b_bits[1]; // @[src/main/scala/regular/StructuralExactBooth8.scala 17:21]
  wire  b0 = io_b_bits[0]; // @[src/main/scala/regular/StructuralExactBooth8.scala 18:21]
  assign io_neg = io_b_bits[2]; // @[src/main/scala/regular/StructuralExactBooth8.scala 16:21]
  assign io_zero = io_b_bits == 3'h0 | io_b_bits == 3'h7; // @[src/main/scala/regular/StructuralExactBooth8.scala 21:34]
  assign io_two = io_b_bits == 3'h3 | io_b_bits == 3'h4; // @[src/main/scala/regular/StructuralExactBooth8.scala 22:34]
  assign io_one = b1 ^ b0; // @[src/main/scala/regular/StructuralExactBooth8.scala 23:18]
endmodule
module KMap_1Row_Approx(
  input         clock,
  input         reset,
  input  [7:0]  io_a, // @[src/main/scala/regular/KMap_Mixed_Approx.scala 11:14]
  input  [7:0]  io_b, // @[src/main/scala/regular/KMap_Mixed_Approx.scala 11:14]
  output [15:0] io_product // @[src/main/scala/regular/KMap_Mixed_Approx.scala 11:14]
);
  wire [2:0] encoders_0_io_b_bits; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_0_io_neg; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_0_io_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_0_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_0_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire [2:0] encoders_1_io_b_bits; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_1_io_neg; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_1_io_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_1_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_1_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire [2:0] encoders_2_io_b_bits; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_2_io_neg; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_2_io_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_2_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire  encoders_2_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
  wire [8:0] b_extended = {io_b,1'h0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 19:23]
  wire  a_is_zero = io_a == 8'h0; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 23:24]
  wire [2:0] b_bits = b_extended[2:0]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 30:28]
  wire  neg = b_bits[2]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 36:23]
  wire  zero = b_bits == 3'h0 | b_bits == 3'h7; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 37:35]
  wire  row_is_zero = zero | a_is_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 38:30]
  wire  _negs_0_T = ~row_is_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 40:25]
  wire  negs_0 = neg & ~row_is_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 40:22]
  wire  a_bit = io_a[0]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 44:36]
  wire  pp_bits__0 = _negs_0_T & (a_bit ^ neg); // @[src/main/scala/regular/KMap_Mixed_Approx.scala 45:38]
  wire  a_bit_1 = io_a[1]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 44:36]
  wire  pp_bits__1 = _negs_0_T & (a_bit_1 ^ neg); // @[src/main/scala/regular/KMap_Mixed_Approx.scala 45:38]
  wire  a_bit_2 = io_a[2]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 44:36]
  wire  pp_bits__2 = _negs_0_T & (a_bit_2 ^ neg); // @[src/main/scala/regular/KMap_Mixed_Approx.scala 45:38]
  wire  a_bit_3 = io_a[3]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 44:36]
  wire  pp_bits__3 = _negs_0_T & (a_bit_3 ^ neg); // @[src/main/scala/regular/KMap_Mixed_Approx.scala 45:38]
  wire  a_bit_4 = io_a[4]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 44:36]
  wire  pp_bits__4 = _negs_0_T & (a_bit_4 ^ neg); // @[src/main/scala/regular/KMap_Mixed_Approx.scala 45:38]
  wire  a_bit_5 = io_a[5]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 44:36]
  wire  pp_bits__5 = _negs_0_T & (a_bit_5 ^ neg); // @[src/main/scala/regular/KMap_Mixed_Approx.scala 45:38]
  wire  a_bit_6 = io_a[6]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 44:36]
  wire  pp_bits__6 = _negs_0_T & (a_bit_6 ^ neg); // @[src/main/scala/regular/KMap_Mixed_Approx.scala 45:38]
  wire  a_bit_7 = io_a[7]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 44:36]
  wire  pp_bits__7 = _negs_0_T & (a_bit_7 ^ neg); // @[src/main/scala/regular/KMap_Mixed_Approx.scala 45:38]
  wire [8:0] _pp_ext_T_1 = {pp_bits__7,pp_bits__7,pp_bits__6,pp_bits__5,pp_bits__4,pp_bits__3,pp_bits__2,pp_bits__1,
    pp_bits__0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 47:35]
  wire [15:0] pp_ext = {{7{_pp_ext_T_1[8]}},_pp_ext_T_1}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 47:50]
  wire  _negs_1_T = ~encoders_0_io_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 61:25]
  wire  negs_1 = encoders_0_io_neg & ~encoders_0_io_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 61:22]
  wire  sel_a = a_bit & encoders_0_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  pp_bits_1_0 = (sel_a ^ encoders_0_io_neg) & _negs_1_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_1 = a_bit_1 & encoders_0_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_1 = a_bit & encoders_0_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_1 = sel_a_1 | sel_2a_1; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_1_1 = (data_bit_1 ^ encoders_0_io_neg) & _negs_1_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_2 = a_bit_2 & encoders_0_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_2 = a_bit_1 & encoders_0_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_2 = sel_a_2 | sel_2a_2; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_1_2 = (data_bit_2 ^ encoders_0_io_neg) & _negs_1_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_3 = a_bit_3 & encoders_0_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_3 = a_bit_2 & encoders_0_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_3 = sel_a_3 | sel_2a_3; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_1_3 = (data_bit_3 ^ encoders_0_io_neg) & _negs_1_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_4 = a_bit_4 & encoders_0_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_4 = a_bit_3 & encoders_0_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_4 = sel_a_4 | sel_2a_4; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_1_4 = (data_bit_4 ^ encoders_0_io_neg) & _negs_1_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_5 = a_bit_5 & encoders_0_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_5 = a_bit_4 & encoders_0_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_5 = sel_a_5 | sel_2a_5; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_1_5 = (data_bit_5 ^ encoders_0_io_neg) & _negs_1_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_6 = a_bit_6 & encoders_0_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_6 = a_bit_5 & encoders_0_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_6 = sel_a_6 | sel_2a_6; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_1_6 = (data_bit_6 ^ encoders_0_io_neg) & _negs_1_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_7 = a_bit_7 & encoders_0_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_7 = a_bit_6 & encoders_0_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_7 = sel_a_7 | sel_2a_7; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_1_7 = (data_bit_7 ^ encoders_0_io_neg) & _negs_1_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_2a_8 = a_bit_7 & encoders_0_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_8 = sel_a_7 | sel_2a_8; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_1_8 = (data_bit_8 ^ encoders_0_io_neg) & _negs_1_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire [8:0] _pp_ext_T_4 = {pp_bits_1_8,pp_bits_1_7,pp_bits_1_6,pp_bits_1_5,pp_bits_1_4,pp_bits_1_3,pp_bits_1_2,
    pp_bits_1_1,pp_bits_1_0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 75:35]
  wire [15:0] pp_ext_1 = {{7{_pp_ext_T_4[8]}},_pp_ext_T_4}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 75:50]
  wire [17:0] _rows_1_T = {pp_ext_1, 2'h0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 76:25]
  wire  _negs_2_T = ~encoders_1_io_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 61:25]
  wire  negs_2 = encoders_1_io_neg & ~encoders_1_io_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 61:22]
  wire  sel_a_9 = a_bit & encoders_1_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  pp_bits_2_0 = (sel_a_9 ^ encoders_1_io_neg) & _negs_2_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_10 = a_bit_1 & encoders_1_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_10 = a_bit & encoders_1_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_10 = sel_a_10 | sel_2a_10; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_2_1 = (data_bit_10 ^ encoders_1_io_neg) & _negs_2_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_11 = a_bit_2 & encoders_1_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_11 = a_bit_1 & encoders_1_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_11 = sel_a_11 | sel_2a_11; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_2_2 = (data_bit_11 ^ encoders_1_io_neg) & _negs_2_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_12 = a_bit_3 & encoders_1_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_12 = a_bit_2 & encoders_1_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_12 = sel_a_12 | sel_2a_12; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_2_3 = (data_bit_12 ^ encoders_1_io_neg) & _negs_2_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_13 = a_bit_4 & encoders_1_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_13 = a_bit_3 & encoders_1_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_13 = sel_a_13 | sel_2a_13; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_2_4 = (data_bit_13 ^ encoders_1_io_neg) & _negs_2_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_14 = a_bit_5 & encoders_1_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_14 = a_bit_4 & encoders_1_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_14 = sel_a_14 | sel_2a_14; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_2_5 = (data_bit_14 ^ encoders_1_io_neg) & _negs_2_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_15 = a_bit_6 & encoders_1_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_15 = a_bit_5 & encoders_1_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_15 = sel_a_15 | sel_2a_15; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_2_6 = (data_bit_15 ^ encoders_1_io_neg) & _negs_2_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_16 = a_bit_7 & encoders_1_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_16 = a_bit_6 & encoders_1_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_16 = sel_a_16 | sel_2a_16; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_2_7 = (data_bit_16 ^ encoders_1_io_neg) & _negs_2_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_2a_17 = a_bit_7 & encoders_1_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_17 = sel_a_16 | sel_2a_17; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_2_8 = (data_bit_17 ^ encoders_1_io_neg) & _negs_2_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire [8:0] _pp_ext_T_7 = {pp_bits_2_8,pp_bits_2_7,pp_bits_2_6,pp_bits_2_5,pp_bits_2_4,pp_bits_2_3,pp_bits_2_2,
    pp_bits_2_1,pp_bits_2_0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 75:35]
  wire [15:0] pp_ext_2 = {{7{_pp_ext_T_7[8]}},_pp_ext_T_7}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 75:50]
  wire [19:0] _rows_2_T = {pp_ext_2, 4'h0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 76:25]
  wire  _negs_3_T = ~encoders_2_io_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 61:25]
  wire  negs_3 = encoders_2_io_neg & ~encoders_2_io_zero; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 61:22]
  wire  sel_a_18 = a_bit & encoders_2_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  pp_bits_3_0 = (sel_a_18 ^ encoders_2_io_neg) & _negs_3_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_19 = a_bit_1 & encoders_2_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_19 = a_bit & encoders_2_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_19 = sel_a_19 | sel_2a_19; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_3_1 = (data_bit_19 ^ encoders_2_io_neg) & _negs_3_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_20 = a_bit_2 & encoders_2_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_20 = a_bit_1 & encoders_2_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_20 = sel_a_20 | sel_2a_20; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_3_2 = (data_bit_20 ^ encoders_2_io_neg) & _negs_3_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_21 = a_bit_3 & encoders_2_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_21 = a_bit_2 & encoders_2_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_21 = sel_a_21 | sel_2a_21; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_3_3 = (data_bit_21 ^ encoders_2_io_neg) & _negs_3_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_22 = a_bit_4 & encoders_2_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_22 = a_bit_3 & encoders_2_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_22 = sel_a_22 | sel_2a_22; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_3_4 = (data_bit_22 ^ encoders_2_io_neg) & _negs_3_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_23 = a_bit_5 & encoders_2_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_23 = a_bit_4 & encoders_2_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_23 = sel_a_23 | sel_2a_23; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_3_5 = (data_bit_23 ^ encoders_2_io_neg) & _negs_3_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_24 = a_bit_6 & encoders_2_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_24 = a_bit_5 & encoders_2_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_24 = sel_a_24 | sel_2a_24; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_3_6 = (data_bit_24 ^ encoders_2_io_neg) & _negs_3_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_a_25 = a_bit_7 & encoders_2_io_one; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 68:28]
  wire  sel_2a_25 = a_bit_6 & encoders_2_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_25 = sel_a_25 | sel_2a_25; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_3_7 = (data_bit_25 ^ encoders_2_io_neg) & _negs_3_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire  sel_2a_26 = a_bit_7 & encoders_2_io_two; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 69:30]
  wire  data_bit_26 = sel_a_25 | sel_2a_26; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 70:30]
  wire  pp_bits_3_8 = (data_bit_26 ^ encoders_2_io_neg) & _negs_3_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 72:40]
  wire [8:0] _pp_ext_T_10 = {pp_bits_3_8,pp_bits_3_7,pp_bits_3_6,pp_bits_3_5,pp_bits_3_4,pp_bits_3_3,pp_bits_3_2,
    pp_bits_3_1,pp_bits_3_0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 75:35]
  wire [15:0] pp_ext_3 = {{7{_pp_ext_T_10[8]}},_pp_ext_T_10}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 75:50]
  wire [21:0] _rows_3_T = {pp_ext_3, 6'h0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 76:25]
  wire [15:0] rows_1 = _rows_1_T[15:0]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 21:18 76:15]
  wire [15:0] _GEN_0 = {{15'd0}, negs_0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 84:22]
  wire [15:0] _sum_T = rows_1 | _GEN_0; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 84:22]
  wire [15:0] _sum_T_2 = pp_ext + _sum_T; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 83:21]
  wire [2:0] _sum_T_3 = {negs_1, 2'h0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 85:40]
  wire [15:0] rows_2 = _rows_2_T[15:0]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 21:18 76:15]
  wire [15:0] _GEN_1 = {{13'd0}, _sum_T_3}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 85:22]
  wire [15:0] _sum_T_4 = rows_2 | _GEN_1; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 85:22]
  wire [15:0] _sum_T_6 = _sum_T_2 + _sum_T_4; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 84:40]
  wire [4:0] _sum_T_7 = {negs_2, 4'h0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 86:40]
  wire [15:0] rows_3 = _rows_3_T[15:0]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 21:18 76:15]
  wire [15:0] _GEN_2 = {{11'd0}, _sum_T_7}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 86:22]
  wire [15:0] _sum_T_8 = rows_3 | _GEN_2; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 86:22]
  wire [15:0] _sum_T_10 = _sum_T_6 + _sum_T_8; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 85:47]
  wire [6:0] _sum_T_11 = {negs_3, 6'h0}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 87:29]
  wire [15:0] _GEN_3 = {{9'd0}, _sum_T_11}; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 86:47]
  ExactEncoder encoders_0 ( // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
    .io_b_bits(encoders_0_io_b_bits),
    .io_neg(encoders_0_io_neg),
    .io_zero(encoders_0_io_zero),
    .io_two(encoders_0_io_two),
    .io_one(encoders_0_io_one)
  );
  ExactEncoder encoders_1 ( // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
    .io_b_bits(encoders_1_io_b_bits),
    .io_neg(encoders_1_io_neg),
    .io_zero(encoders_1_io_zero),
    .io_two(encoders_1_io_two),
    .io_one(encoders_1_io_one)
  );
  ExactEncoder encoders_2 ( // @[src/main/scala/regular/KMap_Mixed_Approx.scala 27:56]
    .io_b_bits(encoders_2_io_b_bits),
    .io_neg(encoders_2_io_neg),
    .io_zero(encoders_2_io_zero),
    .io_two(encoders_2_io_two),
    .io_one(encoders_2_io_one)
  );
  assign io_product = _sum_T_10 + _GEN_3; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 89:21]
  assign encoders_0_io_b_bits = b_extended[4:2]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 30:28]
  assign encoders_1_io_b_bits = b_extended[6:4]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 30:28]
  assign encoders_2_io_b_bits = b_extended[8:6]; // @[src/main/scala/regular/KMap_Mixed_Approx.scala 30:28]
endmodule
