module KMap_4Row_WithZG(
  input         clock,
  input         reset,
  input  [7:0]  io_a, // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 8:14]
  input  [7:0]  io_b, // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 8:14]
  output [15:0] io_product // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 8:14]
);
  wire [8:0] b_extended = {io_b,1'h0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 15:23]
  wire  a_is_zero = io_a == 8'h0; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 20:24]
  wire [2:0] b_bits = b_extended[2:0]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 23:28]
  wire  neg = b_bits[2]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 24:21]
  wire  zero = b_bits == 3'h0 | b_bits == 3'h7; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 25:33]
  wire  row_is_zero = zero | a_is_zero; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 28:28]
  wire  _neg_bits_0_T = ~row_is_zero; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 29:27]
  wire  neg_bits_0 = neg & ~row_is_zero; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 29:24]
  wire  a_bit = io_a[0]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 33:34]
  wire  pp_bits__0 = _neg_bits_0_T & (a_bit ^ neg); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  a_bit_1 = io_a[1]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 33:34]
  wire  pp_bits__1 = _neg_bits_0_T & (a_bit_1 ^ neg); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  a_bit_2 = io_a[2]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 33:34]
  wire  pp_bits__2 = _neg_bits_0_T & (a_bit_2 ^ neg); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  a_bit_3 = io_a[3]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 33:34]
  wire  pp_bits__3 = _neg_bits_0_T & (a_bit_3 ^ neg); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  a_bit_4 = io_a[4]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 33:34]
  wire  pp_bits__4 = _neg_bits_0_T & (a_bit_4 ^ neg); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  a_bit_5 = io_a[5]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 33:34]
  wire  pp_bits__5 = _neg_bits_0_T & (a_bit_5 ^ neg); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  a_bit_6 = io_a[6]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 33:34]
  wire  pp_bits__6 = _neg_bits_0_T & (a_bit_6 ^ neg); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  a_bit_7 = io_a[7]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 33:34]
  wire  pp_bits__7 = _neg_bits_0_T & (a_bit_7 ^ neg); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire [8:0] _pp_ext_T_1 = {pp_bits__7,pp_bits__7,pp_bits__6,pp_bits__5,pp_bits__4,pp_bits__3,pp_bits__2,pp_bits__1,
    pp_bits__0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 37:33]
  wire [15:0] pp_ext = {{7{_pp_ext_T_1[8]}},_pp_ext_T_1}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 37:48]
  wire [2:0] b_bits_1 = b_extended[4:2]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 23:28]
  wire  neg_1 = b_bits_1[2]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 24:21]
  wire  zero_1 = b_bits_1 == 3'h0 | b_bits_1 == 3'h7; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 25:33]
  wire  row_is_zero_1 = zero_1 | a_is_zero; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 28:28]
  wire  _neg_bits_1_T = ~row_is_zero_1; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 29:27]
  wire  neg_bits_1 = neg_1 & ~row_is_zero_1; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 29:24]
  wire  pp_bits_1_0 = _neg_bits_1_T & (a_bit ^ neg_1); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_1_1 = _neg_bits_1_T & (a_bit_1 ^ neg_1); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_1_2 = _neg_bits_1_T & (a_bit_2 ^ neg_1); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_1_3 = _neg_bits_1_T & (a_bit_3 ^ neg_1); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_1_4 = _neg_bits_1_T & (a_bit_4 ^ neg_1); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_1_5 = _neg_bits_1_T & (a_bit_5 ^ neg_1); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_1_6 = _neg_bits_1_T & (a_bit_6 ^ neg_1); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_1_7 = _neg_bits_1_T & (a_bit_7 ^ neg_1); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire [8:0] _pp_ext_T_4 = {pp_bits_1_7,pp_bits_1_7,pp_bits_1_6,pp_bits_1_5,pp_bits_1_4,pp_bits_1_3,pp_bits_1_2,
    pp_bits_1_1,pp_bits_1_0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 37:33]
  wire [15:0] pp_ext_1 = {{7{_pp_ext_T_4[8]}},_pp_ext_T_4}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 37:48]
  wire [17:0] _rows_1_T = {pp_ext_1, 2'h0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 38:23]
  wire [2:0] b_bits_2 = b_extended[6:4]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 23:28]
  wire  neg_2 = b_bits_2[2]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 24:21]
  wire  zero_2 = b_bits_2 == 3'h0 | b_bits_2 == 3'h7; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 25:33]
  wire  row_is_zero_2 = zero_2 | a_is_zero; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 28:28]
  wire  _neg_bits_2_T = ~row_is_zero_2; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 29:27]
  wire  neg_bits_2 = neg_2 & ~row_is_zero_2; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 29:24]
  wire  pp_bits_2_0 = _neg_bits_2_T & (a_bit ^ neg_2); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_2_1 = _neg_bits_2_T & (a_bit_1 ^ neg_2); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_2_2 = _neg_bits_2_T & (a_bit_2 ^ neg_2); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_2_3 = _neg_bits_2_T & (a_bit_3 ^ neg_2); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_2_4 = _neg_bits_2_T & (a_bit_4 ^ neg_2); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_2_5 = _neg_bits_2_T & (a_bit_5 ^ neg_2); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_2_6 = _neg_bits_2_T & (a_bit_6 ^ neg_2); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_2_7 = _neg_bits_2_T & (a_bit_7 ^ neg_2); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire [8:0] _pp_ext_T_7 = {pp_bits_2_7,pp_bits_2_7,pp_bits_2_6,pp_bits_2_5,pp_bits_2_4,pp_bits_2_3,pp_bits_2_2,
    pp_bits_2_1,pp_bits_2_0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 37:33]
  wire [15:0] pp_ext_2 = {{7{_pp_ext_T_7[8]}},_pp_ext_T_7}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 37:48]
  wire [19:0] _rows_2_T = {pp_ext_2, 4'h0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 38:23]
  wire [2:0] b_bits_3 = b_extended[8:6]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 23:28]
  wire  neg_3 = b_bits_3[2]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 24:21]
  wire  zero_3 = b_bits_3 == 3'h0 | b_bits_3 == 3'h7; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 25:33]
  wire  row_is_zero_3 = zero_3 | a_is_zero; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 28:28]
  wire  _neg_bits_3_T = ~row_is_zero_3; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 29:27]
  wire  neg_bits_3 = neg_3 & ~row_is_zero_3; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 29:24]
  wire  pp_bits_3_0 = _neg_bits_3_T & (a_bit ^ neg_3); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_3_1 = _neg_bits_3_T & (a_bit_1 ^ neg_3); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_3_2 = _neg_bits_3_T & (a_bit_2 ^ neg_3); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_3_3 = _neg_bits_3_T & (a_bit_3 ^ neg_3); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_3_4 = _neg_bits_3_T & (a_bit_4 ^ neg_3); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_3_5 = _neg_bits_3_T & (a_bit_5 ^ neg_3); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_3_6 = _neg_bits_3_T & (a_bit_6 ^ neg_3); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire  pp_bits_3_7 = _neg_bits_3_T & (a_bit_7 ^ neg_3); // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 34:36]
  wire [8:0] _pp_ext_T_10 = {pp_bits_3_7,pp_bits_3_7,pp_bits_3_6,pp_bits_3_5,pp_bits_3_4,pp_bits_3_3,pp_bits_3_2,
    pp_bits_3_1,pp_bits_3_0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 37:33]
  wire [15:0] pp_ext_3 = {{7{_pp_ext_T_10[8]}},_pp_ext_T_10}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 37:48]
  wire [21:0] _rows_3_T = {pp_ext_3, 6'h0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 38:23]
  wire [15:0] rows_1 = _rows_1_T[15:0]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 17:18 38:13]
  wire [15:0] _GEN_0 = {{15'd0}, neg_bits_0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:32]
  wire [15:0] _sum_T = rows_1 | _GEN_0; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:32]
  wire [15:0] _sum_T_2 = pp_ext + _sum_T; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:21]
  wire [2:0] _sum_T_3 = {neg_bits_1, 2'h0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:87]
  wire [15:0] rows_2 = _rows_2_T[15:0]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 17:18 38:13]
  wire [15:0] _GEN_1 = {{13'd0}, _sum_T_3}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:65]
  wire [15:0] _sum_T_4 = rows_2 | _GEN_1; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:65]
  wire [15:0] _sum_T_6 = _sum_T_2 + _sum_T_4; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:54]
  wire [4:0] _sum_T_7 = {neg_bits_2, 4'h0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:127]
  wire [15:0] rows_3 = _rows_3_T[15:0]; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 17:18 38:13]
  wire [15:0] _GEN_2 = {{11'd0}, _sum_T_7}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:105]
  wire [15:0] _sum_T_8 = rows_3 | _GEN_2; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:105]
  wire [15:0] _sum_T_10 = _sum_T_6 + _sum_T_8; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:94]
  wire [6:0] _sum_T_11 = {neg_bits_3, 6'h0}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:156]
  wire [15:0] _GEN_3 = {{9'd0}, _sum_T_11}; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 41:134]
  assign io_product = _sum_T_10 + _GEN_3; // @[src/main/scala/regular/step1_zerogating/KMap_4Row_WithZG.scala 42:21]
endmodule
