module ExactEncoder(
  input  [2:0] io_b_bits, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_neg, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_zero, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_two, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_one // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
);
  wire  b1 = io_b_bits[1]; // @[src/main/scala/regular/StructuralExactBooth8.scala 17:21]
  wire  b0 = io_b_bits[0]; // @[src/main/scala/regular/StructuralExactBooth8.scala 18:21]
  assign io_neg = io_b_bits[2]; // @[src/main/scala/regular/StructuralExactBooth8.scala 16:21]
  assign io_zero = io_b_bits == 3'h0 | io_b_bits == 3'h7; // @[src/main/scala/regular/StructuralExactBooth8.scala 21:34]
  assign io_two = io_b_bits == 3'h3 | io_b_bits == 3'h4; // @[src/main/scala/regular/StructuralExactBooth8.scala 22:34]
  assign io_one = b1 ^ b0; // @[src/main/scala/regular/StructuralExactBooth8.scala 23:18]
endmodule
module KMap_V3_3Row_Approx(
  input         clock,
  input         reset,
  input  [7:0]  io_a, // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 9:14]
  input  [7:0]  io_b, // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 9:14]
  output [15:0] io_product // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 9:14]
);
  wire [2:0] encoders_0_io_b_bits; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 23:56]
  wire  encoders_0_io_neg; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 23:56]
  wire  encoders_0_io_zero; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 23:56]
  wire  encoders_0_io_two; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 23:56]
  wire  encoders_0_io_one; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 23:56]
  wire [8:0] b_extended = {io_b,1'h0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 16:23]
  wire [2:0] b_bits = b_extended[2:0]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 26:28]
  wire  neg = b_bits[2]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 27:21]
  wire  zero = b_bits == 3'h0 | b_bits == 3'h7; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 28:33]
  wire  _neg_bits_0_T = ~zero; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 36:29]
  wire  neg_bits_0 = neg & ~zero; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 36:26]
  wire  is_100 = b_bits == 3'h4; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 40:29]
  wire  a_bit = io_a[0]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 42:38]
  wire  approx_bit = _neg_bits_0_T & (a_bit ^ neg); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 45:36]
  wire  exact_bit = _neg_bits_0_T & neg; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 46:35]
  wire  pp_bits__0 = is_100 ? exact_bit : approx_bit; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 48:28]
  wire  a_bit_1 = io_a[1]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 42:38]
  wire  approx_bit_1 = _neg_bits_0_T & (a_bit_1 ^ neg); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 45:36]
  wire  pp_bits__1 = is_100 ? approx_bit : approx_bit_1; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 48:28]
  wire  a_bit_3 = io_a[2]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 42:38]
  wire  approx_bit_2 = _neg_bits_0_T & (a_bit_3 ^ neg); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 45:36]
  wire  pp_bits__2 = is_100 ? approx_bit_1 : approx_bit_2; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 48:28]
  wire  a_bit_4 = io_a[3]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 42:38]
  wire  approx_bit_3 = _neg_bits_0_T & (a_bit_4 ^ neg); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 45:36]
  wire  pp_bits__3 = is_100 ? approx_bit_2 : approx_bit_3; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 48:28]
  wire  a_bit_5 = io_a[4]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 42:38]
  wire  approx_bit_4 = _neg_bits_0_T & (a_bit_5 ^ neg); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 45:36]
  wire  pp_bits__4 = is_100 ? approx_bit_3 : approx_bit_4; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 48:28]
  wire  a_bit_6 = io_a[5]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 42:38]
  wire  approx_bit_5 = _neg_bits_0_T & (a_bit_6 ^ neg); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 45:36]
  wire  pp_bits__5 = is_100 ? approx_bit_4 : approx_bit_5; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 48:28]
  wire  a_bit_7 = io_a[6]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 42:38]
  wire  approx_bit_6 = _neg_bits_0_T & (a_bit_7 ^ neg); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 45:36]
  wire  pp_bits__6 = is_100 ? approx_bit_5 : approx_bit_6; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 48:28]
  wire  a_bit_8 = io_a[7]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 42:38]
  wire  approx_bit_7 = _neg_bits_0_T & (a_bit_8 ^ neg); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 45:36]
  wire  pp_bits__7 = is_100 ? approx_bit_6 : approx_bit_7; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 48:28]
  wire  pp_bits__8 = is_100 ? approx_bit_7 : approx_bit_7; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 48:28]
  wire [8:0] _pp_ext_T_1 = {pp_bits__8,pp_bits__7,pp_bits__6,pp_bits__5,pp_bits__4,pp_bits__3,pp_bits__2,pp_bits__1,
    pp_bits__0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 82:33]
  wire [15:0] pp_ext = {{7{_pp_ext_T_1[8]}},_pp_ext_T_1}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 82:48]
  wire [2:0] b_bits_1 = b_extended[4:2]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 26:28]
  wire  neg_1 = b_bits_1[2]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 27:21]
  wire  zero_1 = b_bits_1 == 3'h0 | b_bits_1 == 3'h7; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 28:33]
  wire  _neg_bits_1_T = ~zero_1; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 36:29]
  wire  neg_bits_1 = neg_1 & ~zero_1; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 36:26]
  wire  pp_bits_1_0 = _neg_bits_1_T & (a_bit ^ neg_1); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_1_1 = _neg_bits_1_T & (a_bit_1 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_1_2 = _neg_bits_1_T & (a_bit_3 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_1_3 = _neg_bits_1_T & (a_bit_4 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_1_4 = _neg_bits_1_T & (a_bit_5 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_1_5 = _neg_bits_1_T & (a_bit_6 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_1_6 = _neg_bits_1_T & (a_bit_7 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_1_7 = _neg_bits_1_T & (a_bit_8 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire [8:0] _pp_ext_T_4 = {pp_bits_1_7,pp_bits_1_7,pp_bits_1_6,pp_bits_1_5,pp_bits_1_4,pp_bits_1_3,pp_bits_1_2,
    pp_bits_1_1,pp_bits_1_0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 82:33]
  wire [15:0] pp_ext_1 = {{7{_pp_ext_T_4[8]}},_pp_ext_T_4}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 82:48]
  wire [17:0] _rows_1_T = {pp_ext_1, 2'h0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 83:23]
  wire [2:0] b_bits_2 = b_extended[6:4]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 26:28]
  wire  neg_2 = b_bits_2[2]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 27:21]
  wire  zero_2 = b_bits_2 == 3'h0 | b_bits_2 == 3'h7; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 28:33]
  wire  _neg_bits_2_T = ~zero_2; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 36:29]
  wire  neg_bits_2 = neg_2 & ~zero_2; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 36:26]
  wire  pp_bits_2_0 = _neg_bits_2_T & (a_bit ^ neg_2); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_2_1 = _neg_bits_2_T & (a_bit_1 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_2_2 = _neg_bits_2_T & (a_bit_3 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_2_3 = _neg_bits_2_T & (a_bit_4 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_2_4 = _neg_bits_2_T & (a_bit_5 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_2_5 = _neg_bits_2_T & (a_bit_6 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_2_6 = _neg_bits_2_T & (a_bit_7 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire  pp_bits_2_7 = _neg_bits_2_T & (a_bit_8 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 54:33]
  wire [8:0] _pp_ext_T_7 = {pp_bits_2_7,pp_bits_2_7,pp_bits_2_6,pp_bits_2_5,pp_bits_2_4,pp_bits_2_3,pp_bits_2_2,
    pp_bits_2_1,pp_bits_2_0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 82:33]
  wire [15:0] pp_ext_2 = {{7{_pp_ext_T_7[8]}},_pp_ext_T_7}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 82:48]
  wire [19:0] _rows_2_T = {pp_ext_2, 4'h0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 83:23]
  wire  _neg_bits_3_T = ~encoders_0_io_zero; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 68:31]
  wire  neg_bits_3 = encoders_0_io_neg & ~encoders_0_io_zero; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 68:28]
  wire  sel_a = a_bit & encoders_0_io_one; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 74:28]
  wire  pp_bits_3_0 = (sel_a ^ encoders_0_io_neg) & _neg_bits_3_T; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 78:42]
  wire  sel_a_1 = a_bit_1 & encoders_0_io_one; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 74:28]
  wire  sel_2a_1 = a_bit & encoders_0_io_two; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 75:30]
  wire  data_bit_1 = sel_a_1 | sel_2a_1; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 76:30]
  wire  pp_bits_3_1 = (data_bit_1 ^ encoders_0_io_neg) & _neg_bits_3_T; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 78:42]
  wire  sel_a_2 = a_bit_3 & encoders_0_io_one; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 74:28]
  wire  sel_2a_2 = a_bit_1 & encoders_0_io_two; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 75:30]
  wire  data_bit_2 = sel_a_2 | sel_2a_2; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 76:30]
  wire  pp_bits_3_2 = (data_bit_2 ^ encoders_0_io_neg) & _neg_bits_3_T; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 78:42]
  wire  sel_a_3 = a_bit_4 & encoders_0_io_one; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 74:28]
  wire  sel_2a_3 = a_bit_3 & encoders_0_io_two; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 75:30]
  wire  data_bit_3 = sel_a_3 | sel_2a_3; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 76:30]
  wire  pp_bits_3_3 = (data_bit_3 ^ encoders_0_io_neg) & _neg_bits_3_T; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 78:42]
  wire  sel_a_4 = a_bit_5 & encoders_0_io_one; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 74:28]
  wire  sel_2a_4 = a_bit_4 & encoders_0_io_two; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 75:30]
  wire  data_bit_4 = sel_a_4 | sel_2a_4; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 76:30]
  wire  pp_bits_3_4 = (data_bit_4 ^ encoders_0_io_neg) & _neg_bits_3_T; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 78:42]
  wire  sel_a_5 = a_bit_6 & encoders_0_io_one; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 74:28]
  wire  sel_2a_5 = a_bit_5 & encoders_0_io_two; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 75:30]
  wire  data_bit_5 = sel_a_5 | sel_2a_5; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 76:30]
  wire  pp_bits_3_5 = (data_bit_5 ^ encoders_0_io_neg) & _neg_bits_3_T; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 78:42]
  wire  sel_a_6 = a_bit_7 & encoders_0_io_one; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 74:28]
  wire  sel_2a_6 = a_bit_6 & encoders_0_io_two; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 75:30]
  wire  data_bit_6 = sel_a_6 | sel_2a_6; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 76:30]
  wire  pp_bits_3_6 = (data_bit_6 ^ encoders_0_io_neg) & _neg_bits_3_T; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 78:42]
  wire  sel_a_7 = a_bit_8 & encoders_0_io_one; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 74:28]
  wire  sel_2a_7 = a_bit_7 & encoders_0_io_two; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 75:30]
  wire  data_bit_7 = sel_a_7 | sel_2a_7; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 76:30]
  wire  pp_bits_3_7 = (data_bit_7 ^ encoders_0_io_neg) & _neg_bits_3_T; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 78:42]
  wire  sel_2a_8 = a_bit_8 & encoders_0_io_two; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 75:30]
  wire  data_bit_8 = sel_a_7 | sel_2a_8; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 76:30]
  wire  pp_bits_3_8 = (data_bit_8 ^ encoders_0_io_neg) & _neg_bits_3_T; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 78:42]
  wire [8:0] _pp_ext_T_10 = {pp_bits_3_8,pp_bits_3_7,pp_bits_3_6,pp_bits_3_5,pp_bits_3_4,pp_bits_3_3,pp_bits_3_2,
    pp_bits_3_1,pp_bits_3_0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 82:33]
  wire [15:0] pp_ext_3 = {{7{_pp_ext_T_10[8]}},_pp_ext_T_10}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 82:48]
  wire [21:0] _rows_3_T = {pp_ext_3, 6'h0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 83:23]
  wire [2:0] operands_5 = {neg_bits_1, 2'h0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 95:24]
  wire [4:0] operands_6 = {neg_bits_2, 4'h0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 96:24]
  wire [6:0] operands_7 = {neg_bits_3, 6'h0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 97:24]
  wire [15:0] rows_1 = _rows_1_T[15:0]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 18:18 83:13]
  wire [15:0] _sum_T_1 = pp_ext + rows_1; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 100:31]
  wire [15:0] rows_2 = _rows_2_T[15:0]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 18:18 83:13]
  wire [15:0] _sum_T_3 = _sum_T_1 + rows_2; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 100:31]
  wire [15:0] rows_3 = _rows_3_T[15:0]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 18:18 83:13]
  wire [15:0] _sum_T_5 = _sum_T_3 + rows_3; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 100:31]
  wire [15:0] _GEN_0 = {{15'd0}, neg_bits_0}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 100:31]
  wire [15:0] _sum_T_7 = _sum_T_5 + _GEN_0; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 100:31]
  wire [15:0] _GEN_1 = {{13'd0}, operands_5}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 100:31]
  wire [15:0] _sum_T_9 = _sum_T_7 + _GEN_1; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 100:31]
  wire [15:0] _GEN_2 = {{11'd0}, operands_6}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 100:31]
  wire [15:0] _sum_T_11 = _sum_T_9 + _GEN_2; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 100:31]
  wire [15:0] _GEN_3 = {{9'd0}, operands_7}; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 100:31]
  ExactEncoder encoders_0 ( // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 23:56]
    .io_b_bits(encoders_0_io_b_bits),
    .io_neg(encoders_0_io_neg),
    .io_zero(encoders_0_io_zero),
    .io_two(encoders_0_io_two),
    .io_one(encoders_0_io_one)
  );
  assign io_product = _sum_T_11 + _GEN_3; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 101:21]
  assign encoders_0_io_b_bits = b_extended[8:6]; // @[src/main/scala/regular/KMap_V3_Mixed_Approx.scala 26:28]
endmodule
