module ExactEncoder(
  input  [2:0] io_b_bits, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_neg, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_two, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_one // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
);
  wire  b1 = io_b_bits[1]; // @[src/main/scala/regular/StructuralExactBooth8.scala 17:21]
  wire  b0 = io_b_bits[0]; // @[src/main/scala/regular/StructuralExactBooth8.scala 18:21]
  assign io_neg = io_b_bits[2]; // @[src/main/scala/regular/StructuralExactBooth8.scala 16:21]
  assign io_two = io_b_bits == 3'h3 | io_b_bits == 3'h4; // @[src/main/scala/regular/StructuralExactBooth8.scala 22:34]
  assign io_one = b1 ^ b0; // @[src/main/scala/regular/StructuralExactBooth8.scala 23:18]
endmodule
module RegularBooth8_KMap_PZ_BARC(
  input         clock,
  input         reset,
  input  [7:0]  io_a, // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 10:14]
  input  [7:0]  io_b, // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 10:14]
  output [15:0] io_product // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 10:14]
);
  wire [2:0] encoders_exact_0_io_b_bits; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 24:51]
  wire  encoders_exact_0_io_neg; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 24:51]
  wire  encoders_exact_0_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 24:51]
  wire  encoders_exact_0_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 24:51]
  wire [2:0] encoders_exact_1_io_b_bits; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 24:51]
  wire  encoders_exact_1_io_neg; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 24:51]
  wire  encoders_exact_1_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 24:51]
  wire  encoders_exact_1_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 24:51]
  wire [7:0] a_signed = io_a; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 16:23]
  wire  a_is_zero = io_a == 8'h0; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 18:24]
  wire [8:0] b_extended = {io_b,1'h0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 19:23]
  wire [2:0] b_bits = b_extended[2:0]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 27:28]
  wire  zero = b_bits == 3'h0 | b_bits == 3'h7; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 32:35]
  wire  neg = b_bits[2]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 33:20]
  wire  _neg_bits_0_T = ~zero; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 34:29]
  wire  neg_bits_0 = neg & ~zero; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 34:26]
  wire  a_bit = io_a[0]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 38:36]
  wire  pp_bits__0 = _neg_bits_0_T & (a_bit ^ neg); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  a_bit_1 = io_a[1]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 38:36]
  wire  pp_bits__1 = _neg_bits_0_T & (a_bit_1 ^ neg); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  a_bit_2 = io_a[2]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 38:36]
  wire  pp_bits__2 = _neg_bits_0_T & (a_bit_2 ^ neg); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  a_bit_3 = io_a[3]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 38:36]
  wire  pp_bits__3 = _neg_bits_0_T & (a_bit_3 ^ neg); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  a_bit_4 = io_a[4]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 38:36]
  wire  pp_bits__4 = _neg_bits_0_T & (a_bit_4 ^ neg); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  a_bit_5 = io_a[5]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 38:36]
  wire  pp_bits__5 = _neg_bits_0_T & (a_bit_5 ^ neg); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  a_bit_6 = io_a[6]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 38:36]
  wire  pp_bits__6 = _neg_bits_0_T & (a_bit_6 ^ neg); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  a_bit_7 = io_a[7]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 38:36]
  wire  pp_bits__7 = _neg_bits_0_T & (a_bit_7 ^ neg); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire [8:0] pp_sint = {pp_bits__7,pp_bits__7,pp_bits__6,pp_bits__5,pp_bits__4,pp_bits__3,pp_bits__2,pp_bits__1,
    pp_bits__0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 43:29]
  wire [15:0] pp_ext = {{7{pp_sint[8]}},pp_sint}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 44:36]
  wire [2:0] b_bits_1 = b_extended[4:2]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 27:28]
  wire  zero_1 = b_bits_1 == 3'h0 | b_bits_1 == 3'h7; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 32:35]
  wire  neg_1 = b_bits_1[2]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 33:20]
  wire  _neg_bits_1_T = ~zero_1; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 34:29]
  wire  neg_bits_1 = neg_1 & ~zero_1; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 34:26]
  wire  pp_bits_1_0 = _neg_bits_1_T & (a_bit ^ neg_1); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  pp_bits_1_1 = _neg_bits_1_T & (a_bit_1 ^ neg_1); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  pp_bits_1_2 = _neg_bits_1_T & (a_bit_2 ^ neg_1); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  pp_bits_1_3 = _neg_bits_1_T & (a_bit_3 ^ neg_1); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  pp_bits_1_4 = _neg_bits_1_T & (a_bit_4 ^ neg_1); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  pp_bits_1_5 = _neg_bits_1_T & (a_bit_5 ^ neg_1); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  pp_bits_1_6 = _neg_bits_1_T & (a_bit_6 ^ neg_1); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire  pp_bits_1_7 = _neg_bits_1_T & (a_bit_7 ^ neg_1); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 39:31]
  wire [8:0] pp_sint_1 = {pp_bits_1_7,pp_bits_1_7,pp_bits_1_6,pp_bits_1_5,pp_bits_1_4,pp_bits_1_3,pp_bits_1_2,
    pp_bits_1_1,pp_bits_1_0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 43:29]
  wire [15:0] pp_ext_1 = {{7{pp_sint_1[8]}},pp_sint_1}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 44:36]
  wire [17:0] _rows_1_T = {pp_ext_1, 2'h0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 45:25]
  wire  sel_a = a_bit & encoders_exact_0_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  neg_2 = encoders_exact_0_io_neg; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 28:19 49:11]
  wire  pp_bits_2_0 = sel_a ^ neg_2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_1 = a_bit_1 & encoders_exact_0_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_1 = a_bit & encoders_exact_0_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_1 = sel_a_1 | sel_2a_1; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_2_1 = data_bit_1 ^ neg_2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_2 = a_bit_2 & encoders_exact_0_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_2 = a_bit_1 & encoders_exact_0_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_2 = sel_a_2 | sel_2a_2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_2_2 = data_bit_2 ^ neg_2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_3 = a_bit_3 & encoders_exact_0_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_3 = a_bit_2 & encoders_exact_0_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_3 = sel_a_3 | sel_2a_3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_2_3 = data_bit_3 ^ neg_2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_4 = a_bit_4 & encoders_exact_0_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_4 = a_bit_3 & encoders_exact_0_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_4 = sel_a_4 | sel_2a_4; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_2_4 = data_bit_4 ^ neg_2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_5 = a_bit_5 & encoders_exact_0_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_5 = a_bit_4 & encoders_exact_0_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_5 = sel_a_5 | sel_2a_5; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_2_5 = data_bit_5 ^ neg_2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_6 = a_bit_6 & encoders_exact_0_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_6 = a_bit_5 & encoders_exact_0_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_6 = sel_a_6 | sel_2a_6; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_2_6 = data_bit_6 ^ neg_2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_7 = a_bit_7 & encoders_exact_0_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_7 = a_bit_6 & encoders_exact_0_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_7 = sel_a_7 | sel_2a_7; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_2_7 = data_bit_7 ^ neg_2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_2a_8 = a_bit_7 & encoders_exact_0_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_8 = sel_a_7 | sel_2a_8; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_2_8 = data_bit_8 ^ neg_2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire [8:0] pp_sint_2 = {pp_bits_2_8,pp_bits_2_7,pp_bits_2_6,pp_bits_2_5,pp_bits_2_4,pp_bits_2_3,pp_bits_2_2,
    pp_bits_2_1,pp_bits_2_0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 66:29]
  wire [15:0] pp_ext_2 = {{7{pp_sint_2[8]}},pp_sint_2}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 67:36]
  wire [19:0] _rows_2_T = {pp_ext_2, 4'h0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 68:25]
  wire  sel_a_9 = a_bit & encoders_exact_1_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  neg_3 = encoders_exact_1_io_neg; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 28:19 49:11]
  wire  pp_bits_3_0 = sel_a_9 ^ neg_3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_10 = a_bit_1 & encoders_exact_1_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_10 = a_bit & encoders_exact_1_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_10 = sel_a_10 | sel_2a_10; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_3_1 = data_bit_10 ^ neg_3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_11 = a_bit_2 & encoders_exact_1_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_11 = a_bit_1 & encoders_exact_1_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_11 = sel_a_11 | sel_2a_11; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_3_2 = data_bit_11 ^ neg_3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_12 = a_bit_3 & encoders_exact_1_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_12 = a_bit_2 & encoders_exact_1_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_12 = sel_a_12 | sel_2a_12; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_3_3 = data_bit_12 ^ neg_3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_13 = a_bit_4 & encoders_exact_1_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_13 = a_bit_3 & encoders_exact_1_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_13 = sel_a_13 | sel_2a_13; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_3_4 = data_bit_13 ^ neg_3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_14 = a_bit_5 & encoders_exact_1_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_14 = a_bit_4 & encoders_exact_1_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_14 = sel_a_14 | sel_2a_14; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_3_5 = data_bit_14 ^ neg_3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_15 = a_bit_6 & encoders_exact_1_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_15 = a_bit_5 & encoders_exact_1_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_15 = sel_a_15 | sel_2a_15; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_3_6 = data_bit_15 ^ neg_3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_a_16 = a_bit_7 & encoders_exact_1_io_one; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 60:28]
  wire  sel_2a_16 = a_bit_6 & encoders_exact_1_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_16 = sel_a_16 | sel_2a_16; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_3_7 = data_bit_16 ^ neg_3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire  sel_2a_17 = a_bit_7 & encoders_exact_1_io_two; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 61:30]
  wire  data_bit_17 = sel_a_16 | sel_2a_17; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 62:30]
  wire  pp_bits_3_8 = data_bit_17 ^ neg_3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 63:32]
  wire [8:0] pp_sint_3 = {pp_bits_3_8,pp_bits_3_7,pp_bits_3_6,pp_bits_3_5,pp_bits_3_4,pp_bits_3_3,pp_bits_3_2,
    pp_bits_3_1,pp_bits_3_0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 66:29]
  wire [15:0] pp_ext_3 = {{7{pp_sint_3[8]}},pp_sint_3}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 67:36]
  wire [21:0] _rows_3_T = {pp_ext_3, 6'h0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 68:25]
  wire [15:0] rows_1 = _rows_1_T[15:0]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 21:18 45:15]
  wire [15:0] _GEN_0 = {{15'd0}, neg_bits_0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 74:20]
  wire [15:0] r1 = rows_1 | _GEN_0; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 74:20]
  wire [2:0] _r2_T = {neg_bits_1, 2'h0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 75:42]
  wire [15:0] rows_2 = _rows_2_T[15:0]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 21:18 68:15]
  wire [15:0] _GEN_1 = {{13'd0}, _r2_T}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 75:20]
  wire [15:0] r2 = rows_2 | _GEN_1; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 75:20]
  wire [4:0] _r3_T = {neg_2, 4'h0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 76:42]
  wire [15:0] rows_3 = _rows_3_T[15:0]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 21:18 68:15]
  wire [15:0] _GEN_2 = {{11'd0}, _r3_T}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 76:20]
  wire [15:0] r3 = rows_3 | _GEN_2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 76:20]
  wire [6:0] n3 = {neg_3, 6'h0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 77:31]
  wire  row0_is_100 = b_bits == 3'h4; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 80:38]
  wire  barc_en = row0_is_100 & ~a_is_zero; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 81:29]
  wire [15:0] _mw_T = {{8{a_signed[7]}},a_signed}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 83:27]
  wire [15:0] mw = 16'sh0 - $signed(_mw_T); // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 83:34]
  wire  barc_bits_0 = mw[0] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_1 = mw[1] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_2 = mw[2] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_3 = mw[3] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_4 = mw[4] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_5 = mw[5] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_6 = mw[6] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_7 = mw[7] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_8 = mw[8] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_9 = mw[9] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_10 = mw[10] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_11 = mw[11] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_12 = mw[12] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_13 = mw[13] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_14 = mw[14] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire  barc_bits_15 = mw[15] & barc_en; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 86:27]
  wire [7:0] barc_op_lo = {barc_bits_7,barc_bits_6,barc_bits_5,barc_bits_4,barc_bits_3,barc_bits_2,barc_bits_1,
    barc_bits_0}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 88:27]
  wire [15:0] barc_op = {barc_bits_15,barc_bits_14,barc_bits_13,barc_bits_12,barc_bits_11,barc_bits_10,barc_bits_9,
    barc_bits_8,barc_op_lo}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 88:27]
  wire [15:0] _sum_T_1 = pp_ext + r1; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 90:16]
  wire [15:0] _sum_T_3 = _sum_T_1 + r2; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 90:21]
  wire [15:0] _sum_T_5 = _sum_T_3 + r3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 90:26]
  wire [15:0] _GEN_3 = {{9'd0}, n3}; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 90:31]
  wire [15:0] _sum_T_7 = _sum_T_5 + _GEN_3; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 90:31]
  ExactEncoder encoders_exact_0 ( // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 24:51]
    .io_b_bits(encoders_exact_0_io_b_bits),
    .io_neg(encoders_exact_0_io_neg),
    .io_two(encoders_exact_0_io_two),
    .io_one(encoders_exact_0_io_one)
  );
  ExactEncoder encoders_exact_1 ( // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 24:51]
    .io_b_bits(encoders_exact_1_io_b_bits),
    .io_neg(encoders_exact_1_io_neg),
    .io_two(encoders_exact_1_io_two),
    .io_one(encoders_exact_1_io_one)
  );
  assign io_product = _sum_T_7 + barc_op; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 91:21]
  assign encoders_exact_0_io_b_bits = b_extended[6:4]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 27:28]
  assign encoders_exact_1_io_b_bits = b_extended[8:6]; // @[src/main/scala/regular/RegularBooth8_KMap_PZ_BARC.scala 27:28]
endmodule
