module ApproxEncoderOpt(
  input  [2:0] io_b_bits, // @[src/main/scala/regular/RegularBooth8FullOpt.scala 8:14]
  output       io_neg, // @[src/main/scala/regular/RegularBooth8FullOpt.scala 8:14]
  output       io_zero, // @[src/main/scala/regular/RegularBooth8FullOpt.scala 8:14]
  output       io_one // @[src/main/scala/regular/RegularBooth8FullOpt.scala 8:14]
);
  assign io_neg = io_b_bits[2]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 16:21]
  assign io_zero = io_b_bits == 3'h0 | io_b_bits == 3'h7; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 21:34]
  assign io_one = ~io_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 23:14]
endmodule
module ExactEncoder(
  input  [2:0] io_b_bits, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_neg, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_zero, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_two, // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
  output       io_one // @[src/main/scala/regular/StructuralExactBooth8.scala 8:14]
);
  wire  b1 = io_b_bits[1]; // @[src/main/scala/regular/StructuralExactBooth8.scala 17:21]
  wire  b0 = io_b_bits[0]; // @[src/main/scala/regular/StructuralExactBooth8.scala 18:21]
  assign io_neg = io_b_bits[2]; // @[src/main/scala/regular/StructuralExactBooth8.scala 16:21]
  assign io_zero = io_b_bits == 3'h0 | io_b_bits == 3'h7; // @[src/main/scala/regular/StructuralExactBooth8.scala 21:34]
  assign io_two = io_b_bits == 3'h3 | io_b_bits == 3'h4; // @[src/main/scala/regular/StructuralExactBooth8.scala 22:34]
  assign io_one = b1 ^ b0; // @[src/main/scala/regular/StructuralExactBooth8.scala 23:18]
endmodule
module RegularBooth8FullOpt(
  input         clock,
  input         reset,
  input  [7:0]  io_a, // @[src/main/scala/regular/RegularBooth8FullOpt.scala 28:14]
  input  [7:0]  io_b, // @[src/main/scala/regular/RegularBooth8FullOpt.scala 28:14]
  output [15:0] io_product // @[src/main/scala/regular/RegularBooth8FullOpt.scala 28:14]
);
  wire [2:0] encoders_approx_0_io_b_bits; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 42:52]
  wire  encoders_approx_0_io_neg; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 42:52]
  wire  encoders_approx_0_io_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 42:52]
  wire  encoders_approx_0_io_one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 42:52]
  wire [2:0] encoders_approx_1_io_b_bits; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 42:52]
  wire  encoders_approx_1_io_neg; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 42:52]
  wire  encoders_approx_1_io_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 42:52]
  wire  encoders_approx_1_io_one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 42:52]
  wire [2:0] encoders_exact_0_io_b_bits; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
  wire  encoders_exact_0_io_neg; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
  wire  encoders_exact_0_io_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
  wire  encoders_exact_0_io_two; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
  wire  encoders_exact_0_io_one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
  wire [2:0] encoders_exact_1_io_b_bits; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
  wire  encoders_exact_1_io_neg; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
  wire  encoders_exact_1_io_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
  wire  encoders_exact_1_io_two; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
  wire  encoders_exact_1_io_one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
  wire [7:0] a_signed = io_a; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 34:23]
  wire  a_is_zero = io_a == 8'h0; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 35:24]
  wire [8:0] b_extended = {io_b,1'h0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 36:23]
  wire [2:0] b_bits = b_extended[2:0]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 46:28]
  wire  zero = encoders_approx_0_io_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 48:20 55:12]
  wire  row_zero = zero | a_is_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 66:25]
  wire  _neg_bits_0_T = ~row_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 67:27]
  wire  neg = encoders_approx_0_io_neg; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 47:20 54:12]
  wire  neg_bits_0 = neg & ~row_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 67:24]
  wire  a_bit = io_a[0]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 72:36]
  wire  one = encoders_approx_0_io_one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 50:20 57:12]
  wire  sel_a = a_bit & one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits__0 = (sel_a ^ neg) & _neg_bits_0_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  a_bit_1 = io_a[1]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 72:36]
  wire  sel_a_1 = a_bit_1 & one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits__1 = (sel_a_1 ^ neg) & _neg_bits_0_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  a_bit_3 = io_a[2]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 72:36]
  wire  sel_a_2 = a_bit_3 & one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits__2 = (sel_a_2 ^ neg) & _neg_bits_0_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  a_bit_4 = io_a[3]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 72:36]
  wire  sel_a_3 = a_bit_4 & one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits__3 = (sel_a_3 ^ neg) & _neg_bits_0_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  a_bit_5 = io_a[4]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 72:36]
  wire  sel_a_4 = a_bit_5 & one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits__4 = (sel_a_4 ^ neg) & _neg_bits_0_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  a_bit_6 = io_a[5]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 72:36]
  wire  sel_a_5 = a_bit_6 & one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits__5 = (sel_a_5 ^ neg) & _neg_bits_0_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  a_bit_7 = io_a[6]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 72:36]
  wire  sel_a_6 = a_bit_7 & one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits__6 = (sel_a_6 ^ neg) & _neg_bits_0_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  a_bit_8 = io_a[7]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 72:36]
  wire  sel_a_7 = a_bit_8 & one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits__7 = (sel_a_7 ^ neg) & _neg_bits_0_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire [8:0] pp_sint = {pp_bits__7,pp_bits__7,pp_bits__6,pp_bits__5,pp_bits__4,pp_bits__3,pp_bits__2,pp_bits__1,
    pp_bits__0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 83:27]
  wire [15:0] pp_ext = {{7{pp_sint[8]}},pp_sint}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 84:34]
  wire  zero_1 = encoders_approx_1_io_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 48:20 55:12]
  wire  row_zero_1 = zero_1 | a_is_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 66:25]
  wire  _neg_bits_1_T = ~row_zero_1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 67:27]
  wire  neg_1 = encoders_approx_1_io_neg; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 47:20 54:12]
  wire  neg_bits_1 = neg_1 & ~row_zero_1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 67:24]
  wire  one_1 = encoders_approx_1_io_one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 50:20 57:12]
  wire  sel_a_9 = a_bit & one_1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits_1_0 = (sel_a_9 ^ neg_1) & _neg_bits_1_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_10 = a_bit_1 & one_1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits_1_1 = (sel_a_10 ^ neg_1) & _neg_bits_1_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_11 = a_bit_3 & one_1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits_1_2 = (sel_a_11 ^ neg_1) & _neg_bits_1_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_12 = a_bit_4 & one_1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits_1_3 = (sel_a_12 ^ neg_1) & _neg_bits_1_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_13 = a_bit_5 & one_1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits_1_4 = (sel_a_13 ^ neg_1) & _neg_bits_1_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_14 = a_bit_6 & one_1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits_1_5 = (sel_a_14 ^ neg_1) & _neg_bits_1_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_15 = a_bit_7 & one_1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits_1_6 = (sel_a_15 ^ neg_1) & _neg_bits_1_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_16 = a_bit_8 & one_1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  pp_bits_1_7 = (sel_a_16 ^ neg_1) & _neg_bits_1_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire [8:0] pp_sint_1 = {pp_bits_1_7,pp_bits_1_7,pp_bits_1_6,pp_bits_1_5,pp_bits_1_4,pp_bits_1_3,pp_bits_1_2,
    pp_bits_1_1,pp_bits_1_0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 83:27]
  wire [15:0] pp_ext_1 = {{7{pp_sint_1[8]}},pp_sint_1}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 84:34]
  wire [17:0] _rows_1_T = {pp_ext_1, 2'h0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 86:23]
  wire  zero_2 = encoders_exact_0_io_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 48:20 61:12]
  wire  row_zero_2 = zero_2 | a_is_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 66:25]
  wire  _neg_bits_2_T = ~row_zero_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 67:27]
  wire  neg_2 = encoders_exact_0_io_neg; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 47:20 60:12]
  wire  neg_bits_2 = neg_2 & ~row_zero_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 67:24]
  wire  one_2 = encoders_exact_0_io_one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 50:20 63:12]
  wire  sel_a_18 = a_bit & one_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  two_2 = encoders_exact_0_io_two; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 49:20 62:12]
  wire  pp_bits_2_0 = (sel_a_18 ^ neg_2) & _neg_bits_2_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_19 = a_bit_1 & one_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_19 = a_bit & two_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_19 = sel_a_19 | sel_2a_19; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_2_1 = (data_bit_19 ^ neg_2) & _neg_bits_2_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_20 = a_bit_3 & one_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_20 = a_bit_1 & two_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_20 = sel_a_20 | sel_2a_20; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_2_2 = (data_bit_20 ^ neg_2) & _neg_bits_2_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_21 = a_bit_4 & one_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_21 = a_bit_3 & two_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_21 = sel_a_21 | sel_2a_21; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_2_3 = (data_bit_21 ^ neg_2) & _neg_bits_2_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_22 = a_bit_5 & one_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_22 = a_bit_4 & two_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_22 = sel_a_22 | sel_2a_22; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_2_4 = (data_bit_22 ^ neg_2) & _neg_bits_2_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_23 = a_bit_6 & one_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_23 = a_bit_5 & two_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_23 = sel_a_23 | sel_2a_23; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_2_5 = (data_bit_23 ^ neg_2) & _neg_bits_2_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_24 = a_bit_7 & one_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_24 = a_bit_6 & two_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_24 = sel_a_24 | sel_2a_24; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_2_6 = (data_bit_24 ^ neg_2) & _neg_bits_2_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_25 = a_bit_8 & one_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_25 = a_bit_7 & two_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_25 = sel_a_25 | sel_2a_25; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_2_7 = (data_bit_25 ^ neg_2) & _neg_bits_2_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_2a_26 = a_bit_8 & two_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_26 = sel_a_25 | sel_2a_26; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_2_8 = (data_bit_26 ^ neg_2) & _neg_bits_2_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire [8:0] pp_sint_2 = {pp_bits_2_8,pp_bits_2_7,pp_bits_2_6,pp_bits_2_5,pp_bits_2_4,pp_bits_2_3,pp_bits_2_2,
    pp_bits_2_1,pp_bits_2_0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 83:27]
  wire [15:0] pp_ext_2 = {{7{pp_sint_2[8]}},pp_sint_2}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 84:34]
  wire [19:0] _rows_2_T = {pp_ext_2, 4'h0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 86:23]
  wire  zero_3 = encoders_exact_1_io_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 48:20 61:12]
  wire  row_zero_3 = zero_3 | a_is_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 66:25]
  wire  _neg_bits_3_T = ~row_zero_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 67:27]
  wire  neg_3 = encoders_exact_1_io_neg; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 47:20 60:12]
  wire  neg_bits_3 = neg_3 & ~row_zero_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 67:24]
  wire  one_3 = encoders_exact_1_io_one; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 50:20 63:12]
  wire  sel_a_27 = a_bit & one_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  two_3 = encoders_exact_1_io_two; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 49:20 62:12]
  wire  pp_bits_3_0 = (sel_a_27 ^ neg_3) & _neg_bits_3_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_28 = a_bit_1 & one_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_28 = a_bit & two_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_28 = sel_a_28 | sel_2a_28; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_3_1 = (data_bit_28 ^ neg_3) & _neg_bits_3_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_29 = a_bit_3 & one_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_29 = a_bit_1 & two_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_29 = sel_a_29 | sel_2a_29; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_3_2 = (data_bit_29 ^ neg_3) & _neg_bits_3_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_30 = a_bit_4 & one_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_30 = a_bit_3 & two_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_30 = sel_a_30 | sel_2a_30; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_3_3 = (data_bit_30 ^ neg_3) & _neg_bits_3_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_31 = a_bit_5 & one_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_31 = a_bit_4 & two_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_31 = sel_a_31 | sel_2a_31; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_3_4 = (data_bit_31 ^ neg_3) & _neg_bits_3_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_32 = a_bit_6 & one_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_32 = a_bit_5 & two_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_32 = sel_a_32 | sel_2a_32; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_3_5 = (data_bit_32 ^ neg_3) & _neg_bits_3_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_33 = a_bit_7 & one_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_33 = a_bit_6 & two_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_33 = sel_a_33 | sel_2a_33; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_3_6 = (data_bit_33 ^ neg_3) & _neg_bits_3_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_a_34 = a_bit_8 & one_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 75:26]
  wire  sel_2a_34 = a_bit_7 & two_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_34 = sel_a_34 | sel_2a_34; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_3_7 = (data_bit_34 ^ neg_3) & _neg_bits_3_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire  sel_2a_35 = a_bit_8 & two_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 76:28]
  wire  data_bit_35 = sel_a_34 | sel_2a_35; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 77:28]
  wire  pp_bits_3_8 = (data_bit_35 ^ neg_3) & _neg_bits_3_T; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 79:38]
  wire [8:0] pp_sint_3 = {pp_bits_3_8,pp_bits_3_7,pp_bits_3_6,pp_bits_3_5,pp_bits_3_4,pp_bits_3_3,pp_bits_3_2,
    pp_bits_3_1,pp_bits_3_0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 83:27]
  wire [15:0] pp_ext_3 = {{7{pp_sint_3[8]}},pp_sint_3}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 84:34]
  wire [21:0] _rows_3_T = {pp_ext_3, 6'h0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 86:23]
  wire [15:0] rows_1 = _rows_1_T[15:0]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 38:18 86:13]
  wire [15:0] _GEN_0 = {{15'd0}, neg_bits_0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 91:20]
  wire [15:0] r1 = rows_1 | _GEN_0; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 91:20]
  wire [2:0] _r2_T = {neg_bits_1, 2'h0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 92:42]
  wire [15:0] rows_2 = _rows_2_T[15:0]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 38:18 86:13]
  wire [15:0] _GEN_1 = {{13'd0}, _r2_T}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 92:20]
  wire [15:0] r2 = rows_2 | _GEN_1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 92:20]
  wire [4:0] _r3_T = {neg_bits_2, 4'h0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 93:42]
  wire [15:0] rows_3 = _rows_3_T[15:0]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 38:18 86:13]
  wire [15:0] _GEN_2 = {{11'd0}, _r3_T}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 93:20]
  wire [15:0] r3 = rows_3 | _GEN_2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 93:20]
  wire [6:0] n3 = {neg_bits_3, 6'h0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 94:31]
  wire  row0_is_100 = b_bits == 3'h4; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 97:38]
  wire  barc_en = row0_is_100 & ~a_is_zero; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 98:29]
  wire [15:0] _mw_T = {{8{a_signed[7]}},a_signed}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 100:27]
  wire [15:0] mw = 16'sh0 - $signed(_mw_T); // @[src/main/scala/regular/RegularBooth8FullOpt.scala 100:34]
  wire  barc_bits_0 = mw[0] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_1 = mw[1] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_2 = mw[2] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_3 = mw[3] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_4 = mw[4] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_5 = mw[5] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_6 = mw[6] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_7 = mw[7] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_8 = mw[8] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_9 = mw[9] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_10 = mw[10] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_11 = mw[11] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_12 = mw[12] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_13 = mw[13] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_14 = mw[14] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire  barc_bits_15 = mw[15] & barc_en; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 103:27]
  wire [7:0] barc_op_lo = {barc_bits_7,barc_bits_6,barc_bits_5,barc_bits_4,barc_bits_3,barc_bits_2,barc_bits_1,
    barc_bits_0}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 105:27]
  wire [15:0] barc_op = {barc_bits_15,barc_bits_14,barc_bits_13,barc_bits_12,barc_bits_11,barc_bits_10,barc_bits_9,
    barc_bits_8,barc_op_lo}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 105:27]
  wire [15:0] _sum_T_1 = pp_ext + r1; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 108:16]
  wire [15:0] _sum_T_3 = _sum_T_1 + r2; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 108:21]
  wire [15:0] _sum_T_5 = _sum_T_3 + r3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 108:26]
  wire [15:0] _GEN_3 = {{9'd0}, n3}; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 108:31]
  wire [15:0] _sum_T_7 = _sum_T_5 + _GEN_3; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 108:31]
  ApproxEncoderOpt encoders_approx_0 ( // @[src/main/scala/regular/RegularBooth8FullOpt.scala 42:52]
    .io_b_bits(encoders_approx_0_io_b_bits),
    .io_neg(encoders_approx_0_io_neg),
    .io_zero(encoders_approx_0_io_zero),
    .io_one(encoders_approx_0_io_one)
  );
  ApproxEncoderOpt encoders_approx_1 ( // @[src/main/scala/regular/RegularBooth8FullOpt.scala 42:52]
    .io_b_bits(encoders_approx_1_io_b_bits),
    .io_neg(encoders_approx_1_io_neg),
    .io_zero(encoders_approx_1_io_zero),
    .io_one(encoders_approx_1_io_one)
  );
  ExactEncoder encoders_exact_0 ( // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
    .io_b_bits(encoders_exact_0_io_b_bits),
    .io_neg(encoders_exact_0_io_neg),
    .io_zero(encoders_exact_0_io_zero),
    .io_two(encoders_exact_0_io_two),
    .io_one(encoders_exact_0_io_one)
  );
  ExactEncoder encoders_exact_1 ( // @[src/main/scala/regular/RegularBooth8FullOpt.scala 43:52]
    .io_b_bits(encoders_exact_1_io_b_bits),
    .io_neg(encoders_exact_1_io_neg),
    .io_zero(encoders_exact_1_io_zero),
    .io_two(encoders_exact_1_io_two),
    .io_one(encoders_exact_1_io_one)
  );
  assign io_product = _sum_T_7 + barc_op; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 110:21]
  assign encoders_approx_0_io_b_bits = b_extended[2:0]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 46:28]
  assign encoders_approx_1_io_b_bits = b_extended[4:2]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 46:28]
  assign encoders_exact_0_io_b_bits = b_extended[6:4]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 46:28]
  assign encoders_exact_1_io_b_bits = b_extended[8:6]; // @[src/main/scala/regular/RegularBooth8FullOpt.scala 46:28]
endmodule
