module KMap_V3_Exp2_EmbeddedSchemeD(
  input         clock,
  input         reset,
  input  [7:0]  io_a, // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 7:14]
  input  [7:0]  io_b, // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 7:14]
  output [15:0] io_product // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 7:14]
);
  wire [8:0] b_extended = {io_b,1'h0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 14:23]
  wire [2:0] b_bits = b_extended[2:0]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 20:28]
  wire  neg = b_bits[2]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 21:21]
  wire  zero = b_bits == 3'h0 | b_bits == 3'h7; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 22:33]
  wire  _neg_bits_0_T = ~zero; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 24:27]
  wire  neg_bits_0 = neg & ~zero; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 24:24]
  wire  is_100 = b_bits == 3'h4; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 29:27]
  wire  a_bit = io_a[0]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 31:36]
  wire  approx_bit = _neg_bits_0_T & (a_bit ^ neg); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 34:34]
  wire  exact_bit = _neg_bits_0_T & neg; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 35:33]
  wire  pp_bits__0 = is_100 ? exact_bit : approx_bit; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 37:26]
  wire  a_bit_1 = io_a[1]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 31:36]
  wire  approx_bit_1 = _neg_bits_0_T & (a_bit_1 ^ neg); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 34:34]
  wire  pp_bits__1 = is_100 ? approx_bit : approx_bit_1; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 37:26]
  wire  a_bit_3 = io_a[2]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 31:36]
  wire  approx_bit_2 = _neg_bits_0_T & (a_bit_3 ^ neg); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 34:34]
  wire  pp_bits__2 = is_100 ? approx_bit_1 : approx_bit_2; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 37:26]
  wire  a_bit_4 = io_a[3]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 31:36]
  wire  approx_bit_3 = _neg_bits_0_T & (a_bit_4 ^ neg); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 34:34]
  wire  pp_bits__3 = is_100 ? approx_bit_2 : approx_bit_3; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 37:26]
  wire  a_bit_5 = io_a[4]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 31:36]
  wire  approx_bit_4 = _neg_bits_0_T & (a_bit_5 ^ neg); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 34:34]
  wire  pp_bits__4 = is_100 ? approx_bit_3 : approx_bit_4; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 37:26]
  wire  a_bit_6 = io_a[5]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 31:36]
  wire  approx_bit_5 = _neg_bits_0_T & (a_bit_6 ^ neg); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 34:34]
  wire  pp_bits__5 = is_100 ? approx_bit_4 : approx_bit_5; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 37:26]
  wire  a_bit_7 = io_a[6]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 31:36]
  wire  approx_bit_6 = _neg_bits_0_T & (a_bit_7 ^ neg); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 34:34]
  wire  pp_bits__6 = is_100 ? approx_bit_5 : approx_bit_6; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 37:26]
  wire  a_bit_8 = io_a[7]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 31:36]
  wire  approx_bit_7 = _neg_bits_0_T & (a_bit_8 ^ neg); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 34:34]
  wire  pp_bits__7 = is_100 ? approx_bit_6 : approx_bit_7; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 37:26]
  wire  pp_bits__8 = is_100 ? approx_bit_7 : approx_bit_7; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 37:26]
  wire [8:0] _pp_ext_T_1 = {pp_bits__8,pp_bits__7,pp_bits__6,pp_bits__5,pp_bits__4,pp_bits__3,pp_bits__2,pp_bits__1,
    pp_bits__0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 46:33]
  wire [15:0] pp_ext = {{7{_pp_ext_T_1[8]}},_pp_ext_T_1}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 46:48]
  wire [2:0] b_bits_1 = b_extended[4:2]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 20:28]
  wire  neg_1 = b_bits_1[2]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 21:21]
  wire  zero_1 = b_bits_1 == 3'h0 | b_bits_1 == 3'h7; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 22:33]
  wire  _neg_bits_1_T = ~zero_1; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 24:27]
  wire  neg_bits_1 = neg_1 & ~zero_1; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 24:24]
  wire  pp_bits_1_0 = _neg_bits_1_T & (a_bit ^ neg_1); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_1_1 = _neg_bits_1_T & (a_bit_1 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_1_2 = _neg_bits_1_T & (a_bit_3 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_1_3 = _neg_bits_1_T & (a_bit_4 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_1_4 = _neg_bits_1_T & (a_bit_5 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_1_5 = _neg_bits_1_T & (a_bit_6 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_1_6 = _neg_bits_1_T & (a_bit_7 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_1_7 = _neg_bits_1_T & (a_bit_8 ^ neg_1); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire [8:0] _pp_ext_T_4 = {pp_bits_1_7,pp_bits_1_7,pp_bits_1_6,pp_bits_1_5,pp_bits_1_4,pp_bits_1_3,pp_bits_1_2,
    pp_bits_1_1,pp_bits_1_0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 46:33]
  wire [15:0] pp_ext_1 = {{7{_pp_ext_T_4[8]}},_pp_ext_T_4}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 46:48]
  wire [17:0] _rows_1_T = {pp_ext_1, 2'h0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 47:23]
  wire [2:0] b_bits_2 = b_extended[6:4]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 20:28]
  wire  neg_2 = b_bits_2[2]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 21:21]
  wire  zero_2 = b_bits_2 == 3'h0 | b_bits_2 == 3'h7; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 22:33]
  wire  _neg_bits_2_T = ~zero_2; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 24:27]
  wire  neg_bits_2 = neg_2 & ~zero_2; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 24:24]
  wire  pp_bits_2_0 = _neg_bits_2_T & (a_bit ^ neg_2); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_2_1 = _neg_bits_2_T & (a_bit_1 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_2_2 = _neg_bits_2_T & (a_bit_3 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_2_3 = _neg_bits_2_T & (a_bit_4 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_2_4 = _neg_bits_2_T & (a_bit_5 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_2_5 = _neg_bits_2_T & (a_bit_6 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_2_6 = _neg_bits_2_T & (a_bit_7 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_2_7 = _neg_bits_2_T & (a_bit_8 ^ neg_2); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire [8:0] _pp_ext_T_7 = {pp_bits_2_7,pp_bits_2_7,pp_bits_2_6,pp_bits_2_5,pp_bits_2_4,pp_bits_2_3,pp_bits_2_2,
    pp_bits_2_1,pp_bits_2_0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 46:33]
  wire [15:0] pp_ext_2 = {{7{_pp_ext_T_7[8]}},_pp_ext_T_7}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 46:48]
  wire [19:0] _rows_2_T = {pp_ext_2, 4'h0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 47:23]
  wire [2:0] b_bits_3 = b_extended[8:6]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 20:28]
  wire  neg_3 = b_bits_3[2]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 21:21]
  wire  zero_3 = b_bits_3 == 3'h0 | b_bits_3 == 3'h7; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 22:33]
  wire  _neg_bits_3_T = ~zero_3; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 24:27]
  wire  neg_bits_3 = neg_3 & ~zero_3; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 24:24]
  wire  pp_bits_3_0 = _neg_bits_3_T & (a_bit ^ neg_3); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_3_1 = _neg_bits_3_T & (a_bit_1 ^ neg_3); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_3_2 = _neg_bits_3_T & (a_bit_3 ^ neg_3); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_3_3 = _neg_bits_3_T & (a_bit_4 ^ neg_3); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_3_4 = _neg_bits_3_T & (a_bit_5 ^ neg_3); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_3_5 = _neg_bits_3_T & (a_bit_6 ^ neg_3); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_3_6 = _neg_bits_3_T & (a_bit_7 ^ neg_3); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire  pp_bits_3_7 = _neg_bits_3_T & (a_bit_8 ^ neg_3); // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 42:31]
  wire [8:0] _pp_ext_T_10 = {pp_bits_3_7,pp_bits_3_7,pp_bits_3_6,pp_bits_3_5,pp_bits_3_4,pp_bits_3_3,pp_bits_3_2,
    pp_bits_3_1,pp_bits_3_0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 46:33]
  wire [15:0] pp_ext_3 = {{7{_pp_ext_T_10[8]}},_pp_ext_T_10}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 46:48]
  wire [21:0] _rows_3_T = {pp_ext_3, 6'h0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 47:23]
  wire [6:0] _op4_T = {neg_bits_3, 6'h0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 55:33]
  wire [4:0] _op4_T_1 = {neg_bits_2, 4'h0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 55:61]
  wire [6:0] _GEN_0 = {{2'd0}, _op4_T_1}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 55:39]
  wire [6:0] _op4_T_2 = _op4_T | _GEN_0; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 55:39]
  wire [2:0] _op4_T_3 = {neg_bits_1, 2'h0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 55:89]
  wire [6:0] _GEN_1 = {{4'd0}, _op4_T_3}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 55:67]
  wire [6:0] _op4_T_4 = _op4_T_2 | _GEN_1; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 55:67]
  wire [6:0] _GEN_2 = {{6'd0}, neg_bits_0}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 55:95]
  wire [6:0] op4 = _op4_T_4 | _GEN_2; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 55:95]
  wire [15:0] rows_1 = _rows_1_T[15:0]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 16:18 47:13]
  wire [15:0] _sum_T_1 = pp_ext + rows_1; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 57:17]
  wire [15:0] rows_2 = _rows_2_T[15:0]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 16:18 47:13]
  wire [15:0] _sum_T_3 = _sum_T_1 + rows_2; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 57:23]
  wire [15:0] rows_3 = _rows_3_T[15:0]; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 16:18 47:13]
  wire [15:0] _sum_T_5 = _sum_T_3 + rows_3; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 57:29]
  wire [15:0] _GEN_3 = {{9'd0}, op4}; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 57:35]
  assign io_product = _sum_T_5 + _GEN_3; // @[src/main/scala/regular/KMap_V3_Exp2_EmbeddedSchemeD.scala 59:21]
endmodule
